greeting = "Hello, world!"
messages = [
    "This is the first message.",
    "This is the second message."
]

[pages]
    [pages.home]
    title = "Home page"
    description = "This is the home page."
