greeting = "¡Hola, mundo!"
messages = [
    "Este es el primer mensaje.",
    "Este es el segundo mensaje."
]

[pages]
    [pages.home]
    title = "Página de Inicio"
    description = "Esta es la página de inicio."
