name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Update rustup
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.repository == 'daschdev/languages-rs'
        run: rustup self update

      - name: Install Rust
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.repository == 'daschdev/languages-rs'
        run: |
          rustup set profile minimal
          rustup update stable
          rustup default stable

      - name: Build zip file
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.repository == 'daschdev/languages-rs'
        run: zip -r source_code.zip examples src .gitignore Cargo.lock Cargo.toml CHANGELOG.md LICENSE README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.repository == 'daschdev/languages-rs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: source_code.zip
          body_path: CHANGELOG.md
          draft: true

      - name: Publish to Crates.io
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.repository == 'daschdev/languages-rs'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
